package main

import (
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
	"strings"
)

func main() {
	i := 0
	for {
		URL := "https://nekobot.xyz/api/image?type=hentai"
		err := download(URL)
		if err != nil {
			log.Fatal(err)
		}
		i++
		fmt.Println(string(i) + " Hentai Downloading")
	}
}

func download(URL string) error {

	type AutoGenerated struct {
		Success bool   `json:"success"`
		Message string `json:"message"`
		Color   int    `json:"color"`
		Version string `json:"version"`
	}

	resp, err := http.Get(URL)

	if err != nil {
		return err
	}

	res, er := io.ReadAll(resp.Body)

	if er != nil {
		return er
	}

	var nigger AutoGenerated

	json.Unmarshal(res, &nigger)

	response, err := http.Get(nigger.Message)

	split := strings.Split(nigger.Message, "/")

	fileName := split[len(split)-1]

	if err != nil {
		return err
	}

	defer response.Body.Close()

	if response.StatusCode != 200 {
		return errors.New("Non 200 Response Code: " + string(response.StatusCode))
	}

	os.Mkdir("./hentai", os.ModePerm)

	file, err := os.Create("hentai/" + fileName)

	if err != nil {
		return err
	}
	defer file.Close()

	_, err = io.Copy(file, response.Body)

	if err != nil {
		return err
	}
	return nil
}
