[package]
name = "HentaiDownloader"
version = "1.0.0-Bouki"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde_json = "1.0"
url = "2.3.1"
